name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: 3.12
          spec: 'jyut.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Jyutping'
          options: --onefile, --name "Jyutping", --windowed,--add-data="venv/Lib/site-packages/jyutping/data/*;jyutping/data",--hidden-import="jyutping.data",--hidden-import="pkg_resources.py2_warn"
      - name: Download Zip
        uses: actions/download-artifact@v4
        with:
          name: Jyutping
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/Jyutping.exe
          asset_name: Jyutping.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
